export const FETCH_SONGS = 'FETCH_SONGS'
export const GET_SONG_IMAGE = 'GET_SONG_IMAGE'
export const ADD_SONG = 'ADD_SONG'
export const LIKE_SONG = 'LIKE_SONG'
export const SET_PLAYED_SONG = 'SET_PLAYED_SONG'
